# Generated by Django 3.2.13 on 2022-08-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photocell', models.CharField(blank=True, max_length=10, null=True)),
                ('waterlevel', models.CharField(blank=True, max_length=10, null=True)),
                ('soilmoisture', models.CharField(blank=True, max_length=10, null=True)),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
