# Generated by Django 3.2.13 on 2022-08-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='waterlevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
