# Generated by Django 3.2.13 on 2022-08-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sensors_waterlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='photocell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='soilmoisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
